export const CREATE_PROFESSOR = "CREATE_PROFESSOR";
export const RETRIEVE_PROFESSORS = "RETRIEVE_PROFESSORS";
export const UPDATE_PROFESSOR = "UPDATE_PROFESSOR";
export const DELETE_PROFESSOR = "DELETE_PROFESSOR";
export const DELETE_ALL_PROFESSORS = "DELETE_ALL_PROFESSORS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";